### ISSUE TITLE
[bbclib] Unreasonable structure of transactions

### ISSUE THREAD

**Issue by junkurihara** [beyond-blockchain/bbc1#112]
I just checked the current structure of bbclib, and found that the transaction could be composed in bson and bson+zlib in addition to the original dedicated binary format. The format of a transaction (bson, bson+zlib or dedicated one) is described OUTSIDE data structure. In fact, it is specified by the first 2 bytes of the output of bbclib, i.e., a transaction data, as a flag. I believe that from the following reason, either one of bson or dedicated format should be eliminated from the core structure of bbclib:

- Signatures do not protect the flag in a transaction currently. This implies that attackers can modify such flags of transactions and then users cannot correctly decode such modified transactions. Hence the system could be compromised.
- The definition bbclib is currently ambiguous. IMHO, it should be a small 'core' module to sign/verify/compose/decompose transactions, and should not be a composer of wire formats.

From the above observations, I would like to propose to define (de)composers of wire format, i.e., bson and bson+zlib, as output plugins of bbc1, and fix the transaction format only with the dedicated one.

**Comment by quvox** [comment]
Thanks for your proposal.
As you pointed out, the format should be simpler and clearer. Although bson/bson+zlib format was implemented in v1.0, the default format is still the binary format, and there would not be strong requirements to use bson at this point. (If we have javascript based bbclib and it is widely used, the situation would be different.)

With considering backward compatibility, how about the following ideas?
- We use the first two byte which is not protected by the signature for wire-format identifier
- The default value 0 is for plain binary (same as the current binary format).
- The two-byte identifier of 1 to 6 is for the backward compatibility (will be obsoleted in the near future)
- If someone wants to compress a transaction, a new two-byte identifier will be defined and the wire-format encoder/decoder would be implemented outside bbclib.py

**Comment by junkurihara** [comment]
Hello. I believe the change you proposed looks no problem and promising!

**Comment by quvox** [comment]
Redesigned as in https://github.com/beyond-blockchain/bbc1/blob/develop/docs/BBc1_data_format_ja.md

**Comment by quvox** [comment]
version 1.2 implelents the ideas. Note that serializing/deserializing code in apps need to be modified a bit.
