### ISSUE TITLE
'archive-all' is not a git command

### ISSUE THREAD

**Issue by y-sira** [beyond-blockchain/bbc1#21]
## Environment

- macOS Sierra
- Python 3.6.3 (with pyenv)

```
% ./docker-bbc1.sh gitbuild
git: 'archive-all' is not a git command. See 'git --help'.
mv: rename ../bbc1.tar.gz to ./bbc1.tar.gz: No such file or directory
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /Users/yuki-sh/Projects/bbc1/Dockerfile_git: no such file or directory
rm: bbc1.tar.gz: No such file or directory
```
https://github.com/beyond-blockchain/bbc1/blob/develop/docker/docker-bbc1.sh#L35

**Comment by quvox** [comment]
"archive-all" is an extension of git command. You need to install it by ```pip install git-archive-all```. It also includes in requirements.txt, so that you will have it by ```pip install -r requirements.txt```. We use the extension to include all submodules in the tar ball for docker.
Anyway, we should do it without such an extension.
